services:
  db:
    container_name: db-data
    image: postgres:17.3-alpine
    environment:
      POSTGRES_USER: ${POSTGRESQL_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DB_NAME}
    ports:
      - '${POSTGRESQL_PORT}:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
